name: workflow-run

on:
  workflow_run:
    workflows:
      - echo
    types:
      - completed
  
jobs:
  echo:
    name: just an echo
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.number }}
        name: event.number
