name: echo-push

on:
  push:
  pull_request_review:
  pull_request:
  pull_request_target:

jobs:
  echo:
    name: just an echo
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.number }}
        name: event.number
