---
name: pull-request-target

on:
  pull_request_target:

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git branch
      - run: env
      - uses: hmarr/auto-approve-action@v3
