---
name: pull-request-target

on:
  pull_request_target:

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git branch
      - run: env
      - name: Review
        uses: Garlic-Team/Auto-Review@1.0.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_TYPE: APPROVE
          MESSAGE: 'Good Job 🐢 🧄'
