name: Review assigning

on:
  push:
  workflow_run:
    workflows:
      - echo-push
    types:
      - completed
  pull_request_review:

jobs:
  reviews:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls
      - name: Set reviewers or merge
        uses: sigyl-actions/auto-review-action@master
        with:
          scheme-file: review-scheme.yml