---
name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git branch
      - run: env
      - run: echo ${{ github.event.number }}
        name: event.number
      - name: Set reviewers or merge
        uses: sigyl-actions/auto-review-action@master
        with:
          scheme-file: review-scheme.yml
