---
name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed
  pull_request_review:

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git branch
      - run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"    
      - name: Set reviewers or merge
        uses: sigyl-actions/auto-review-action@master
        with:
          scheme-file: review-scheme.yml
